version: '3'

services:
  web:
    image: django_blog
    container_name: django_blog_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./blog:/manage.py
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mydatabasepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
