# Generated by Django 4.2.3 on 2023-10-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
