# Generated by Django 4.2.3 on 2023-10-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0003_author_following_alter_author_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked_by',
        ),
    ]
