# Generated by Django 4.2.3 on 2023-10-09 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0004_rename_likes_post_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
