# Generated by Django 4.2.3 on 2023-10-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0006_alter_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, default='blog_posts/post_tbs/profile_pic.png', null=True, upload_to='blog_posts/post_tbs/'),
        ),
    ]
