# Generated by Django 4.2.3 on 2023-11-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0007_alter_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(default='blog_posts/post_tbs/profile_pic.png', upload_to='blog_posts/profile_pic/'),
        ),
    ]
