# Generated by Django 4.2.3 on 2023-11-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0008_alter_author_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(default='blog_posts/default/avatar.webp', upload_to='blog_posts/profile_pic/'),
        ),
    ]
